// ==UserScript==
// @name          巴哈姆特-深色主題(測試版)
// @namespace     http://userstyles.org
// @description	  標題：css-巴哈姆特-深色主題
// @author        hbl917070(深海異音)
// @homepage      https://userstyles.org/styles/112515
// @include       http://forum.gamer.com.tw/*
// @include       https://forum.gamer.com.tw/*
// @include       https://forum.gamer.com.tw/opinion/*
// @include       https://forum.gamer.com.tw/vresult2*
// @include       https://forum.gamer.com.tw*
// @include       http://forum.gamer.com.tw/search*
// @include       https://forum.gamer.com.tw/search*
// @include       http://www.youtube.com/*
// @include       https://www.youtube.com/*
// @run-at        document-start
// @grant         GM_addStyle
// @version       0.20170814180941
// ==/UserScript==



/*

重要：此為測試版，不會進行更新

*/



//這裡可以設定『隨機背景圖片』
//前面有『//』(兩條斜線)就是"註解"的意思，不會被執行
//所以如果想要有3張圖片隨機使用，可以把下面的『//ar_bac_img.push("圖片網址");』改成你要的圖片網址，並把前面兩條斜線拿掉
var ar_bac_img = new Array();
ar_bac_img.push("https://truth.bahamut.com.tw/s01/201708/4bacdf20d388654c12bab48dffd88a59.JPG");
ar_bac_img.push("https://truth.bahamut.com.tw/s01/201708/b421d3feca832e19a038477fe5eccbad.JPG");
//ar_bac_img.push("圖片網址");
//ar_bac_img.push("圖片網址");

var bac_img = ar_bac_img[get_random(0, ar_bac_img.length-1)];


function get_random(minNum,maxNum) {
    var n = Math.floor(Math.random() * (maxNum - minNum + 1)) + minNum;
    return n;
}


(function() {


    

    
        var css = "";
if (false || (document.location.href.indexOf("http://forum.gamer.com.tw/") == 0) || (document.location.href.indexOf("https://forum.gamer.com.tw/") == 0))
    
    GM_addStyle(
        `html{
background-image:linear-gradient(90deg,rgba(0,0,0, 0.80) 0%,rgba(0,0,0, 0.20) 100%),  url(`+bac_img+`)!important;
background-attachment: fixed !important; 
background-position:center center!important;
background-repeat: no-repeat !important;
background-size: cover !important;
background-color: #222 !important;}`
    );
    
    GM_addStyle(
        `body{
background-image: none!important;
background-color: rgba(0,0,0,0)!important;`
    ); 
    
    GM_addStyle(`#BH-footer{
background:url(` + ar_bac_img[0] + ` );
background-size:1px 1px;
background-repeat: no-repeat !important;
}
#BH-footer p{
background:url(` + ar_bac_img[1] + ` );
background-size:1px 1px;
background-repeat: no-repeat !important;
}`);
    
    css += [		
		"  /*文字預設的顏色*/",
		"  #BH-background{  ",
		"    color: #FFF !important;",
		"  }",
		"  ",
		"  ",
		"  /*漸變特效（畫面緩緩顯示）*/",
		"  /*@-webkit-keyframes myGradual  {",
		"    0%   {opacity: 0.4;}",
		"    100% {opacity: 1;}",
		"  }",
		"  @-moz-keyframes myGradual  {",
		"    0%   {opacity: 0.4;}",
		"    100% {opacity: 1;}",
		"  }*/",
		"  ",
		"  ",
		"  /*--------------------------------------------------------------*/",
		"  /*2017/08/14 界面大更新*/",
		"  ",
		"  /*文章裡面*/",
		"  ",
		"  ",
		"  /*固定在最上面的工具列*/",
		"  .c-menu__scrolldown{    ",
		"    background-color: rgba(0, 0, 0, 0.70) !important;",
		"    color: #FFF!important;",
		"  }",
		"  .c-menu__scrolldown a,.c-menu__scrolldown h1{",
		"    color: #FFF!important;    ",
		"  }",
		"  .toolbar a:hover{",
		"    color: #87DFFF !important;",
		"  }",
		"  .BH-menuE ,.c-menu , #BH-menu-path{",
		"    border-top: none !important;",
		"  }",
		"  ",
		"  /*關閉動畫*/",
		"  /*.c-menu__scrolldown , #BH-menu-path , .c-fixed--header .is-scroll{",
		"    transition: none  !important;",
		"  }*/",
		"  ",
		"  /*文章區塊*/",
		"  .c-post{",
		"    color: #FFF;",
		"    background-color: hsla(0,0%,13%,0.50);",
		"    border: 1px solid rgba(255,255,255,0.39) !important;",
		"",
		"  }",
		"  /*文章預設文字顏色*/",
		"  .c-article__content{",
		"    color: #FFF;  ",
		"  }",
		"  /*超連結顏色*/",
		"  .c-post a[href]{",
		"    color: #87DFFF;",
		"  }",
		"  ",
		"  /*文章主內容*/",
		"  .c-post__body{",
		"    border-top:solid 1px rgba(255,255,255,0.5) !important;",
		"    padding-top:30px;",
		"  }",
		"  ",
		"  /*作者*/",
		"  .username{",
		"    color:#fff  !important;",
		"  }",
		"  ",
		"  /*時間*/",
		"  .edittime{",
		"    color:rgba(255,255,255,0.7)  !important;",
		"  }",
		"  ",
		"  /*留言區塊*/",
		"  .c-post__footer{",
		"    color: #FFF;",
		"    background-color: rgba(0,0,0,0)!important; ",
		"    border-top:solid 1px rgba(255,255,255,0.5) !important;   ",
		"  }",
		"  .c-reply span{",
		"    color:#FFF;",
		"  }",
		"  .c-reply a[href]{",
		"    color: #87DFFF !important;       ",
		"  }",
		"  .c-reply a[href]:hover{",
		"    text-decoration:underline!important;",
		"  }",
		"  ",
		"  /*右下角的『回覆』*/",
		"  .jumptocomment button{",
		"     background-color: hsla(0,0%,13%,0.50) !important;  ",
		"     border: 1px solid rgba(255,255,255,0.39) !important;  ",
		"  }",
		"  .jumptocomment button:hover{",
		"     border: 1px solid #87DFFF !important; ",
		"  }",
		"  ",
		"  ",
		"  /*留言輸入框*/",
		"  .reply-input{",
		"    background-color: rgba(255,255,255,0.3) !important;",
		"    color: #FFF !important;",
		"    ",
		"  }",
		"  .reply-input div{   ",
		"    color: #FFF !important;",
		"  }",
		"  ",
		"  ",
		"  /*快速回覆*/",
		"  .c-section__main{",
		"    background-color: hsla(0,0%,13%,0.50) !important;",
		"    border: 1px solid rgba(255,255,255,0.39) !important;",
		"    ",
		"  }",
		"  .c-section__main h1{",
		"    color: #FFF !important;",
		"  }",
		"  .ql-editor{",
		"    color: #FFF ;",
		"  }",
		"  .option{",
		"    background-color: rgba(0,0,0,0) !important;",
		"  }",
		"  ",
		"  ",
		"  /*本版熱門推薦*/",
		"  .c-section a{",
		"    color: #FFF ;",
		"  }",
		"  ",
		"  /*上下一頁的按鈕*/",
		"  .c-section__main .next,.c-section__main .prev{",
		"    height:52px;",
		"    margin:-12px 0px;",
		"    line-height:50px!important;",
		"    border-radius:0px !important;",
		"  }",
		"  ",
		"  /*右邊的『切回舊版』視窗*/",
		"  .c-test{    ",
		"    background-color: hsla(0,0%,13%,0.50);",
		"    border: 1px solid rgba(255,255,255,0.39) !important;",
		"  }",
		"  ",
		"  ",
		"  ",
		"  ",
		"  /*右下角『電梯』、『回最上面』、『回列表』*/",
		"  .jumpfloor , .jumpfloor input , .c-quicktool .goback , .c-quicktool .gotop{",
		"    background-color: hsla(0,0%,13%,0.50) !important;",
		"    border: 1px solid rgba(255,255,255,0.39) !important;",
		"    color: #FFF ;",
		"  }",
		"  .jumpfloor input:hover, .c-quicktool .goback:hover , .c-quicktool .gotop:hover{",
		"    border: 1px solid #87DFFF !important;",
		"  }",
		"  ",
		"  /*--------------------------------------------------------------*/",
		"  ",
		"  /*2017/08/14*/",
		"  ",
		"  /*文章列表*/",
		"  .b-list-wrap{",
		"    background-color: hsla(0,0%,13%,0.50)!important; ",
		"    border: 1px solid rgba(255,255,255,0.39) !important;  ",
		"    margin-top:30px!important; ",
		"  } ",
		"  .b-list-wrap td{",
		"     border-bottom: 1px dotted rgba(255,255,255,0.4) !important;  ",
		"  }",
		"  .b-list__row:nth-child(2n+1){",
		"    background-color: rgba(255,255,255,0.05)!important; ",
		"  }",
		"  ",
		"  /*標題列*/",
		"  .b-list__head{",
		"    background-color: rgba(0,0,0,1)!important; ",
		"  }",
		"  ",
		"  /*頂置*/",
		"  .b-list__row--sticky{",
		"    background-color: rgba(30,100,80,0.20) !important;",
		"    border-bottom: 1px dotted rgba(255,255,255,0.4) !important;      ",
		"  }",
		"  ",
		"  /*移入*/",
		"  .b-list-wrap tr:hover{",
		"    background-color: rgba(100,130,120,0.40) !important;",
		"  }",
		"  ",
		"  /*標題醒目的顏色*/",
		"  .is-highlight{",
		"    color:rgba(50,180,190,1) !important;",
		"  }",
		"  ",
		"  /*作者帳號顏色*/",
		"  .b-list__count__user a , .b-list__time__user a ,.b-list__main__pages a{",
		"    color: #87DFFF !important;",
		"  }  ",
		"  .b-list-wrap a{",
		"     color:#FFF !important; ",
		"  }",
		"  ",
		"  /*移入的顏色*/",
		"  .b-list-wrap a:hover{",
		"    color: #87DFFF !important;",
		"  }",
		"  ",
		"  ",
		"  /*icon『圖片』顏色*/",
		"  .icon-photo{",
		"    color: rgba(100,200,150,1) !important;",
		"  }",
		"  /*icon『影片』顏色*/",
		"  .icon-video{",
		"    color: rgba(250,100,150,1) !important;",
		"  }",
		"   /*icon『鎖』顏色*/",
		"  .icon-lock{",
		"    color: rgba(150,100,200,1) !important;",
		"  }",
		"  ",
		"  /*頁碼前面的虛線『>>...』*/",
		"  .b-list__main__pages{",
		"     color: rgba(255,255,255,0.7) !important;",
		"  }",
		"  ",
		"",
		"   /*回到文章列表的動畫顏色*/",
		"   @keyframes highlight  {",
		"    0%   {background: rgba(150,100,100,0.0); }",
		"    50% {background: rgba(150,100,100,0.50); }",
		"    100%   {background: rgba(150,100,100,0.0); }",
		"  }",
		"  @-moz-keyframes highlight  {",
		"    0%   {background: rgba(150,100,100,0.0); }",
		"    50% {background: rgba(150,100,100,0.50); }",
		"    100%   {background: rgba(150,100,100,0.0); }",
		"  }",
		"  @-webkit-keyframes highlight  {",
		"    0%   {background: rgba(150,100,100,0.0); }",
		"    50% {background: rgba(150,100,100,0.50); }",
		"    100%   {background: rgba(150,100,100,0.0); }",
		"  }",
		"  ",
		"  /*文章列表-版本熱門推薦*/",
		"  .b-popular{",
		"    background-color: hsla(0,0%,13%,0.50)!important; ",
		"    border: 1px solid rgba(255,255,255,0.39) !important;  ",
		"  }",
		"  .b-popular a{",
		"    color:#FFF !important; ",
		"  }",
		"  ",
		"  ",
		"  ",
		"  /*上面的類別按鈕*/",
		"  .b-tags a{",
		"    background-color: hsla(0,0%,13%,0.50)!important; ",
		"    outline : 1px solid rgba(255,255,255,0.39) !important;  ",
		"    color:#FFF !important; ",
		"  }",
		"  ",
		"  ",
		"  ",
		"  /*--------------------------------------------------------------*/",
		"  ",
		"  /*2015 - 04 - 16 改版的【上方主選單】----最後修改：2015-05-19*/",
		"  ",
		"  /*顏色*/  ",
		"  .BH-menuE , .BH_menu-search{",
		"    background-color: rgba(0, 0, 0, 0.70) !important;",
		"    color: #000!important;",
		"    /*display:block!important; 讓【搜尋】預設就是展開的狀態*/",
		"  }",
		"  ",
		"  ",
		"  /*↓ ↓ ↓ ↓ ↓ ----自動隱藏(砍掉這部分就不會自動隱藏)----↓ ↓ ↓ ↓ ↓ ↓*/",
		"  /*原始狀態*/",
		"  /*#BH-menu-path {",
		"    opacity: 0; ",
		"    padding: 0px 0px;",
		"    margin : -100px 0px 100px 0px!important; ",
		"  }*/",
		"  /*移入*/",
		"  /*#BH-menu-path:hover {",
		"    opacity:1 ; ",
		"    margin : 0px 0px!important;",
		"  }",
		"  .TOP-bh:hover ~ #BH-background #BH-wrapper #BH-menu-path{",
		"    opacity: 1;   ",
		"    margin : 0px 0px!important;",
		"  }*/",
		"  ",
		"",
		"  ",
		"  /*↑ ↑ ↑ ↑ ↑ ↑----自動隱藏(砍掉這部分就不會自動隱藏)----↑ ↑ ↑ ↑ ↑ ↑*/",
		"  ",
		"",
		"",
		"  ",
		"  .BH-searchC input[type=\'text\'] {/*【搜尋】的文字框*/",
		"   ",
		"    background-color: rgba(255,255,255,0.3) !important;",
		"    color: #FFF !important;",
		"    font-weight:bold !important;",
		"  }",
		"  ",
		"",
		"  ",
		"  ",
		"  /*--------------------------------------------------------------*/",
		"  ",
		"  ",
		"  ",
		"  /*2015 04 26  右上角的【精華】圖示*/ ",
		"  ",
		"  /*圖片可以自行更換，在 url(\'\') 裡面輸入要的圖片網址就行了*/",
		"  .FM-feature{",
		"    background:url(\'https://farm8.staticflickr.com/7718/17275017691_5397eeb0ee_o.png\') no-repeat scroll right top transparent !important;",
		"  }",
		"  ",
		"  ",
		"  /*--------------------------------------------------------------*/",
		"  ",
		"  /*2015-05-16 【通知視窗】*/",
		"  ",
		"  /*整體*/ ",
		"  .TOP-msg {  ",
		"    background-color: hsla(0,0%,15%,0.9) !important;",
		"    color:#FFF !important;",
		"    border:  2px solid #249DB8!important;",
		"  }",
		"  .TOP-msglist div:hover , .TOP-msglist a:hover{/*移到上面時*/",
		"    background-color: rgba(00,00,00,0.95) !important;",
		"  }",
		"  ",
		"  .TOP-msg .new{/*新通知*/",
		"    background-color: rgba(50,100,80,0.5) !important; ",
		"    border:  1px solid rgba(255,255,255,0.39)!important;",
		"  }  ",
		"  ",
		"  .TOP-msgpic {/*圖片底色*/",
		"    background-color: rgba(100,100,100,0.2) !important;",
		"  }",
		"  .TOP-msgbtn {/*最下面那條*/",
		"     background-color: hsla(0,0%,0%,0.2) !important;",
		"     border-top:  2px solid #249DB8 !important;",
		"  }",
		"  .TOP-msg [href]{/*超連結顏色*/",
		"    color:#87DFFF !important;",
		"  }",
		"  .title textarea{/*社團快速留言*/",
		"    background-color: rgba(255,255,255,0.2) !important;",
		"    color: #fff !important;",
		"    border: 1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  ",
		"  /*--------------------------------------------------------------*/",
		"  ",
		"  /*最上面那條（通知、訂閱、推薦）*/",
		"  .TOP-bh{",
		"    background-color: rgba(0, 0, 0, 01.70) !important;",
		"    box-shadow: 0px 0px 0px #000 !important;",
		"  }",
		"  #BH-top-data{",
		"    background-color: rgba(0, 0, 0, 0.0) !important;",
		"  }",
		"  /*最上面的搜尋*/",
		"  #top_search_q{",
		"    /*display: none !important;    */",
		"    background-color: rgba(255, 255, 255, 0.30) !important;",
		"    color: rgba(255, 255, 255, 1) !important;",
		"  }",
		"  ",
		"  ",
		"  /*--------------------------------------------------------------*/  ",
		"  ",
		"  /*【移除FB點讚】*/",
		"  .fb-like{",
		"    display: none !important;",
		"    height: 0px !important;",
		"  }  ",
		"  /*【移除廣告】上面、右邊 */",
		"  #BH-ad_banner , #flySalve , #BH-bigbanner{",
		"    opacity :0 ! important;",
		"    height: 0px !important;",
		"    pointer-events: none !important;",
		"  }",
		"  ",
		"  /*上面的廣告*/",
		"  .a-mercy-d{",
		"    display: block;",
		"    opacity :0 !important;",
		"    height: 0px !important;",
		"    pointer-events: none !important;",
		"    overflow-y:scroll !important;",
		"  }",
		"  ",
		"  /*下面的廣告（2016-10-14）*/",
		"  .forum-bottom-banner{",
		"    opacity :0 !important;",
		"    height: 0px !important;",
		"    pointer-events: none !important;",
		"    overflow-y:scroll !important;",
		"    ",
		"  }",
		"  ",
		"  /*--------------------------------------------------------------*/",
		"  ",
		"  /*最近閱覽看板*/",
		"  .BH-rbox a{",
		"    color: #FFF !important;",
		"  }  ",
		"  /*google搜尋*/",
		"  #BH-search{",
		"    background-color: hsla(0,0%,18%,0.50)!important;",
		"  }",
		"  ",
		"  /*--------------------------------------------------------------*/  ",
		"  ",
		"  /* http://forum.gamer.com.tw/ */",
		"  /*看版首頁*/",
		"  .FM-abox5B{",
		"    background-color: hsla(0,0%,18%,0.00) !important;",
		"  }",
		"  .FM-abox2A  ,.FM-abox8A{",
		"    background-color: hsla(0,0%,18%,0.00) !important;",
		"    color: #DDD !important;",
		"  }",
		"  .BH-lbox{/*要先讓底色透明*/",
		"    background-color: hsla(0,0%,18%,0.50) !important;   ",
		"    border:  1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  ",
		"  .FORUM-master_box1 strong{/*標題*/",
		"    background-color: hsla(0,0%,18%,0.0) !important; ",
		"  }",
		"  ",
		"  /**/",
		"  .FORUM-master_box1 a,.FORUM-master_box1 p{",
		"    color: #FFF !important;",
		"    border:  0px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  .FORUM-master_box1 a:hover{",
		"    color: #87DFFF !important;",
		"  }",
		"  ",
		"  /*每個版的樣式*/",
		"  .FORUM-master_box1 div{",
		"    border:  1px solid rgba(255,255,255,0.39)!important;",
		"    margin-bottom: 5px !important;",
		"    background-color: rgba(0,0,0, 0.5) !important;",
		"  }",
		"  .FORUM-master_box1 div strong{/*標題*/",
		"    background-color: rgba(0,0,0, 0.7) !important;",
		"    border-bottom:   1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  ",
		"   .FM-abox2A  a[href]{",
		"     color: #87DFFF !important;",
		"   }",
		"  ",
		"",
		"  ",
		"   /*達人專區*/ ",
		"   .FM-abox8 a{",
		"     color: #FFF !important;",
		"   } ",
		"  ",
		"  /*最上面的（搜尋）*/",
		"  .BH-search2 input{",
		"    background-color: #000 !important;",
		"    color: #DDD !important;",
		"  }",
		"",
		"  /*文章搜尋的文字顏色*/",
		"  .BH-search2 span{",
		"    color: #000 !important;",
		"  }",
		"  ",
		"  /*--------------------------------------------------------------*/  ",
		"",
		"  /*每個版的首頁*/",
		"  ",
		"  .FM-abox6B a[href]{/*作品介紹*/",
		"    color: #87DFFF !important; ",
		"  }",
		"  .ACG-box span ,.ACG-box p{",
		"    color:#FFF !important;",
		"  }",
		"  ",
		"  /*--------------------------------------------------------------*/  ",
		"  ",
		"  ",
		"  /*文章列表*/",
		"  .fmb tr ,.fmb { ",
		"    background-color: hsla(0,0%,0%,0.10)!important;  ",
		"	  border-collapse: collapse;	",
		"    border:   none !important;",
		"  }",
		"  ",
		"  .fmb tr{",
		"    border-bottom:  0px solid rgba(255,255,255,0.39)!important;",
		"    border:  1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  ",
		"  ",
		"  /*滑鼠移動到上面的顏色*/",
		"  .fmb tr:hover  td{    ",
		"    background-color: rgba(0,0,0,1)!important;",
		"    /*transform: scale(1.2);*/",
		"",
		"  }  ",
		"  ",
		"  ",
		"  /*底色*/",
		"  .fmb td{",
		"    background-color: hsla(0,0%,18%,0.60)!important;",
		"    border-bottom:  none !important;",
		"  } ",
		"  /*文章列表-文字*/",
		"  .FM-blist a{ ",
		"    color: #EEE !important;",
		"    /*font-size:15px;*/  /*讓文章列表的文字變大*/",
		"  }",
		"  /*單數行的底色*/",
		"  .FM-row td{",
		"    background-color: hsla(0,0%,3%,0.50) !important;",
		"    border-bottom:  none !important;",
		"  }",
		"  /*頂置文章的底色*/",
		"  .FM-sticky td{",
		"    background-color: hsla(150,30%,20%,0.40) !important;    ",
		"  }   ",
		"  /*GP數量*/",
		"  .FM-blist4 {",
		"     color: #CC55CC !important;",
		"  } ",
		"",
		"",
		"  /*--------------------------------------------------------------*/  ",
		"  ",
		"  ",
		"  ",
		"  /*推薦\\精華\\達人*/",
		"  .FM-blist1 td{",
		"     background: #000 !important;",
		"     background-color: #000 !important;",
		"  }",
		"  .FM-blist1 a{",
		"    background: none !important;",
		"    border: 1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  .FM-blist1 a:hover{",
		"    border: 1px solid #87DFFF!important;",
		"  }",
		"  /*文章子板 、頁數*/",
		"  .FM-blist2 a ,.FM-blist3 span a{",
		"    color: #87DFFF !important;",
		"  }",
		"  /*文章瀏覽人數*/",
		"  .FM-blist5 {",
		"    color: #CCC !important;",
		"  }",
		"  /*文章列表-作者*/",
		"  .FM-blist5 a,.FM-blist6 a {",
		"    color: #87DFFF !important;",
		"  }",
		"  /*GP篩選*/",
		"  .gplist a,.gplist {",
		"    color: #000 !important;",
		"  }",
		"  ",
		"  ",
		"  /*--------------------------------------------------------------*/  ",
		"  ",
		"  ",
		"  /*    看板首頁    板規    文章列表    精華區*/",
		"  #BH-main_menu,.BH-search2{",
		"    background: none !important;",
		"    background-color: hsla(0,0%,13%,0.50)!important;",
		"    border: 1px solid rgba(255,255,255,0.39);",
		"  }",
		"  #BH-main_menu a{",
		"    color: #FFF !important;    ",
		"  }",
		"  ",
		"  /*文章分類的標籤-框架*/",
		"  .FM-tags{",
		"    border-bottom: 0px solid rgba(255,255,255,0.39) !important;",
		"    margin-bottom: 10px !important;",
		"  }",
		"  /*文章分類的標籤*/",
		"  .FM-tags a{",
		"    background: none !important;",
		"    background-color: hsla(0,0%,13%,0.50) !important; ",
		"    color: #FFF  !important;   ",
		"    border: 1px solid rgba(255,255,255,0.39) !important;",
		"  }",
		"  .FM-tags a:hover{",
		"    border: 1px solid #87DFFF!important;",
		"  }",
		"  /*選中的*/",
		"  #FM-tagsnow{",
		"    background-color: #3C91C9 !important;",
		"    color: #000  !important;    ",
		"  }",
		"",
		"    ",
		"  /*--------------------------------------------------------------*/  ",
		"  ",
		"  ",
		"  /*最上面（文章在哪一個版的文字*/",
		"  #BH-pathbox  a{",
		"    color: #FFF;",
		"  }",
		"  ",
		"  /*--------------------------------------------------------------*/  ",
		"  ",
		"  ",
		"  /*右邊區塊的標題（動漫東萬通、版務*/",
		"  #BH-slave h5{",
		"    background-color: #111 !important;",
		"    background: none ;",
		"    border: 1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  ",
		"  /*右邊區塊（動漫電玩通、版務*/",
		"  .BH-rbox  {",
		"    color: #FFF;",
		"    background-color: hsla(0,0%,13%,0.50); ",
		"	  border: 1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  /*同上的超連結文字*/",
		"  .BH-rbox a[href]{",
		"     color: #87DFFF !important;",
		"  }",
		"  ",
		"",
		"  ",
		"  /*--------------------------------------------------------------*/  ",
		"",
		" ",
		"  ",
		"  ",
		"  /*文章區塊-整體*/",
		"  .FM-cbox1{    ",
		"    background-color: hsla(0,0%,13%,0.50) !important; ",
		"    color: #fff !important;",
		"    margin-bottom :30px !important; ",
		"    border: 1px solid rgba(255,255,255,0.39) !important;",
		"  }",
		"  /*文章當中的超連結*/",
		"  .FM-cbox7 a:link{",
		"    color: #87DFFF !important;",
		"  }/*文章當中點選過得超連結*/",
		"  .FM-cbox7 a:visited{",
		"    color: #C78DFF !important;",
		"  }",
		"  /*文章-作者ID */",
		"  .FM-cbox5 a:link{",
		"    color: #87DFFF !important;",
		"  }",
		"  /*文章勇者區*/",
		"  .FM-cbox2{",
		"    background: none !important;",
		"    color: #fff !important;    ",
		"    border-bottom: 1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  /*勇者區上面的標題*/",
		"  .FM-cbox3{",
		"    background: none !important;",
		"    background-color: #000 !important;  ",
		"    color: #fff !important;  ",
		"    border-bottom: 1px solid rgba(255,255,255,0.39)!important;",
		"  }  ",
		"  ",
		"  .FM-cbox9 {",
		"     border-top:1px  solid rgba(255,255,255,0.39) !important;",
		"  }",
		"  ",
		"  /*文章的GP、BP*/",
		"  .FM-cbox9 p a {",
		"    background: none !important;",
		"    background-color: hsla(0,0%,13%,0.50) !important; ",
		"    color: #87DFFF !important;",
		"  }",
		"  /*看她的文、開啟圖片*/",
		"  .FM-cbox4 a {",
		"    border: 1px solid rgba(255,255,255,0.39) !important;",
		"    background: none !important;",
		"    background-color: rgba(0,0,0,0.4) !important;",
		"    color: #DDD !important;",
		"  }",
		"  .FM-cbox4 a:hover{",
		"    border: 1px solid #87DFFF!important;",
		"  }",
		"  ",
		"  /*檢舉*/",
		"  .FM-cbox10 button{",
		"     background-color: #000 !important;",
		"     color: #DDD !important;",
		"    ",
		"  }",
		"  ",
		"  /*--------------------------------------------------------------*/  ",
		"  ",
		"  /*留言*/",
		"  .FM-cbox10D {",
		"    border-top: 1px solid rgba(255,255,255,0.39) !important ;",
		"    border-bottom: 1px solid rgba(255,255,255,0.39) !important ;",
		"    background-color: hsla(0,0%,13%,0.00) !important; ",
		"  }",
		"  ",
		"  .FM-cbox10D a{     ",
		"    color: #87DFFF !important;  ",
		"    border: 1px solid rgba(255,255,255,0.39)!important; ",
		"    background-color: rgba(0,0,0,0.4) !important; ",
		"    padding: 5px!important;",
		"",
		"    line-height:30px!important;",
		"    ",
		"  }",
		"  .FM-cbox10D a:hover{ ",
		"    border: 1px solid #87DFFF!important;",
		"  }",
		"  ",
		"  /*留言的名字*/",
		"  .FM-msgbg a{",
		"    color: #5588CC !important;  ",
		"  }",
		"  /*留言的日期*/",
		"  .FM-msgbg span{",
		"    color: #558855 !important;  ",
		"  } ",
		"  /*留言區的漸層*/",
		"  .FM-cbox10A,.FM-cbox10{",
		"    background: none !important;",
		"	  border-bottom: 1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  /*留言-輸入框*/",
		"  .FM-cbox10C textarea{",
		"    background-color: rgba(255,255,255,0.2) !important;",
		"    color: #fff !important;",
		"    border: 1px solid rgba(255,255,255,0.39)!important;	",
		"  }",
		"  ",
		"  ",
		"  /*--------------------------------------------------------------*/",
		"  ",
		"  /*快速回復*/",
		"  ",
		"  /*本體 \\ 未登入*/",
		"  .FM-reply , .FM-replyB{",
		"    background-color: hsla(0,0%,13%,0.50) !important; ",
		"    ",
		"    border: 1px solid rgba(255,255,255,0.39)!important;",
		"    color: #DDD !important;",
		"  }",
		"   ",
		"  ",
		"  #reply0{/*輸入框*/",
		"    background-color: rgba(255,255,255,0.2) !important;",
		"    color: #fff !important;",
		"    border: 1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  .FM-replyA input[type=text]{/*驗證碼輸入框*/",
		"    background-color: rgba(255,255,255,0.2) !important;",
		"    color: #fff !important;",
		"    border: 1px solid rgba(255,255,255,0.39)!important;",
		"    width:80px !important;",
		"    padding:  5px;",
		"  }",
		"  .FM-replyC a[style] , .FM-replyA button{/*【button】完整編輯、快速回覆*/",
		"    background-color: rgba(0,0,0,0.4) !important;",
		"    color: #87DFFF !important;",
		"    border: 1px solid rgba(255,255,255,0.39)!important;",
		"    padding:  3px;",
		"  }",
		"  .FM-replyC a[style]:hover , .FM-replyA button:hover{",
		"    border: 1px solid #87DFFF!important;",
		"  }",
		"  ",
		"  /*--------------------------------------------------------------*/  ",
		"  ",
		"   /*避免進階編輯出現背景*/",
		"  .editstyle{",
		"    background: none !important;",
		"    background-color: #FFF!important;",
		"    color: #000!important;",
		"  }",
		"  ",
		"  /*--------------------------------------------------------------*/",
		"  ",
		"  /*下面的 本版熱門推薦*/",
		"  .FM-blist8{",
		"    border: 1px solid rgba(255,255,255,0.39) !important;",
		"    margin-top: 10px !important; ",
		"  }",
		"  .FM-blist8 a{/*移除外框*/",
		"    border:none !important;",
		"  }",
		"",
		"  /*--------------------------------------------------------------*/  ",
		"  ",
		"  /*版權宣告*/",
		"  #BH-footer{",
		"    color: rgba(255,255,255,0.4) !important;",
		"    border:none;",
		"    ",
		"  }",
		"",
		"  /*--------------------------------------------------------------*/",
		"  ",
		"  /*編輯器的按鈕（原始碼、即時瀏覽）*/",
		"  #_bhrte_btn_text,#_bhrte_btn_rte{",
		"    background-color: #CCC;     ",
		"  }",
		"",
		"  /*Google Chrome 編輯器文字矯正*/",
		"  #form1 .FM-lbox3C{",
		"  	color:#CCAACC !important;",
		"  }",
		"",
		"  /*--------------------------------------------------------------*/",
		"  ",
		"  /*看版首頁的【投票區】*/",
		"  .FM-abmbar {",
		"    /*color:#000 !important;",
		"    background-color: #222;   */",
		"    background-color:hsla(0,0%,100%,0)!important;",
		"  }",
		"  ",
		"  ",
		"  /*--------------------------------------------------------------*/  ",
		"  ",
		"  /*各個版的 表格【http://forum.gamer.com.tw/rank.php?c=21】*/",
		"  .BH-table1 , .BH-table1 tr{",
		"    background-color: hsla(0,0%,13%,0.50)!important;",
		"    color: #FFF !important;",
		"    border:  1px solid rgba(255,255,255,0.39)!important;",
		"",
		"  }  ",
		"  .BH-table1 tr td , .BH-table1 tr td a{",
		"    color: #FFF !important; ",
		"  }",
		"  .BH-table1 .bgcolor{",
		"    background-color: hsla(0,0%,23%,0.50)!important;",
		"  }",
		"  .BH-table1 tr td small{",
		"    color: #AAAACC !important;",
		"  }",
		"  ",
		"  ",
		"  .BH-table1,.BH-table1 tr{",
		"    border: none !important;    ",
		"  }",
		"  ",
		"  .BH-table1 td{",
		"    border:  1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  ",
		"  /*--------------------------------------------------------------*/  ",
		"  ",
		"  /*水桶名單 表格【http://forum.gamer.com.tw/water.php?bsn=60076】*/",
		"  .FM-stb1 , .FM-stb1 tr{",
		"    background-color: hsla(0,0%,13%,0.50)!important;",
		"    color: #FFF !important;",
		"  }",
		"  .FM-stb1 tr td , .FM-stb1 tr td a{",
		"    color: #FFF !important; ",
		"  }",
		"  .FM-stb1 tr td span{",
		"    color: #AAFFCC !important;",
		"  }",
		"  ",
		"  ",
		"  /*--------------------------------------------------------------*/   ",
		"  ",
		"  /*精華區索引*/",
		"  /*http://forum.gamer.com.tw/listG.php?bsn=60076*/",
		"  ",
		"  .FM-sbox3B table a{",
		"    color: #FFF !important;",
		"  }",
		"  ",
		"  ",
		"  /*--------------------------------------------------------------*/   ",
		"  /*--------------------------------------------------------------*/   ",
		"  /*--------------------------------------------------------------*/   ",
		"  ",
		"  ",
		"  ",
		"  /*【反轉顏色】*/",
		"  ",
		"  ",
		"  ",
		"  /*【反轉顏色】(公佈欄 公佈欄*/",
		"  .FM-abox5B a[href], .FM-abox5B  a[href] font[color] {",
		"    color: #87DFFF!important;",
		"  }",
		"  ",
		"  ",
		"  /*【文字顏色反轉】（版規*/",
		"  #BH-master div.FM-lbox4 a[href]  , #BH-master div.FM-lbox4  a[href] font[color]{",
		"    color: #87DFFF!important;",
		"  }",
		"",
		"  ",
		"",
		"  /*【反轉顏色】(哈拉區的文章*/",
		"  .FM-cbox7 a[href] , .FM-cbox7  a[href] font[color] {",
		"    color: #87DFFF!important;",
		"  }",
		"",
		"  ",
		"  ",
		"  ",
		" ",
		"  ",
		"  ",
		"  ",
		"  /*--------------------------------------------------------------*/   ",
		"  /*--------------------------------------------------------------*/   ",
		"  /*--------------------------------------------------------------*/   ",
		"  ",
		"  ",
		"  /*本板熱門推薦*/",
		"  .FM-blist8 p:hover{ ",
		"    outline : 1px solid #87DFFF!important;      ",
		"  }",
		"  ",
		"  ",
		"  ",
		"  /*回到文章列表的按鈕、換頁按鈕*/",
		"  .FM-cbox9 .back{               ",
		"    color: #fff!important;",
		"    border: 1px solid rgba(255,255,255,0.39)!important;",
		"    background: url(https://i.imgur.com/1vTZIKi.png) !important;",
		"    background-color: rgba(0,0,0,0.4)!important;",
		"    background-repeat: no-repeat !important;     /*不重複*/",
		"    background-size: 24px 18px !important;         /*自動填滿（contain、cover）*/",
		"    background-position:center center !important; /*對齊位置*/",
		"  }",
		"  ",
		"  .FM-cbox9 .back:hover ,button[name=\'accuse_tip\']:hover , .FM-lbox1 button:hover,.FM-msgbg button:hover{",
		"    border: 1px solid #87DFFF!important;  ",
		"  }",
		"  ",
		"  button[name=\'accuse_tip\'],",
		"  .FM-lbox1 button,",
		"  .FM-msgbg button{",
		"    ",
		"    background-color: rgba(0,0,0,0.4)!important;",
		"    color: #fff!important;",
		"    border: 1px solid rgba(255,255,255,0.39)!important;",
		"    line-height:0px;",
		"  }",
		"  ",
		"",
		"  #BH-pagebtn a:link{  ",
		"    background: rgba(0,0,0,0.4)!important;",
		"    color: #fff!important;",
		"    border: 1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  ",
		"  #BH-pagebtn a{  ",
		"    color: #fff;",
		"  }",
		"  ",
		"  #BH-pagebtn a:hover{  ",
		"    border: 1px solid #87DFFF!important; ",
		"    background: rgba(0,0,0,0.4)!important;",
		"  }",
		"  ",
		"  #BH-pagebtn .pagenow, #BH-pagebtn .no{    ",
		"     border: 1px solid rgba(255,255,255,0.39)!important;  ",
		"  }",
		"  #BH-pagebtn .pagenow:hover{",
		"    background-color: #148aa4!important;",
		"  }",
		"  #BH-pagebtn .no{    ",
		"    background-color: rgba(0,0,0,0.4)!important;",
		"    color: #444!important;",
		"     ",
		"    opacity: 0;",
		"  }",
		"  #BH-pagebtn .no:hover{",
		"    border: 1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  ",
		"  ",
		"  /*動漫電玩通*/",
		"  .BH-qabox1 button{",
		"    background: rgba(0,0,0,0.4)!important;",
		"    color: #fff!important;",
		"    border: 1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  .BH-qabox1 button:hover{",
		"    border: 1px solid #87DFFF!important;",
		"  }",
		"  ",
		"  ",
		"  ",
		"  /*針對【BahaForumPreviewer】的優化（在文章列表顯示內文的插件）2017-02-02*/",
		"  .FM-blist table tr,.FM-blist table ,.FM-blist table td{",
		"      border: none !important;",
		"      background: rgba(0,0,0,0)!important;",
		"      color : rgba(240,255,205,1)!important;",
		"  }",
		"  ",
		"  ",
		"  /*--------------------------------------------------------------*/   ",
		"  /*--------------------------------------------------------------*/   ",
		"  /*--------------------------------------------------------------*/   ",
		"  ",
		"  ",
		"  ",
		"  /*我們了解您不想看到廣告的心情⋯ 若您願意支持巴哈姆特永續經營，請將 gamer.com.tw 加入廣告阻擋工具的白名單中，謝謝 !*/",
		"  body div[style*=\'position: fixed; left: 20px; right: 20px;\']{",
		"    display:block !important;",
		"    opacity :0 !important;",
		"    height: 0px !important;",
		"    pointer-events: none !important;   ",
		"  }",
		"  ",
		"  /*上面的搜尋框*/",
		"  /*#gsc-i-id1{   ",
		"    background: rgba(255,255,255,0.4)!important;",
		"    color:rgba(255,255,255,1)!important;",
		"  }*/",
		"  /*放大鏡的按鈕*/",
		"  /*.gsc-search-button{",
		"    background: rgba(255,255,255,0.4)!important;    ",
		"  }*/",
		"  ",
		"  ",
		"  ",
		"   /*搜尋 2017/05/15*/",
		"  #searchbox{",
		"    background: rgba(255,255,255,0.4)!important;",
		"  }",
		"",
		"  /*修正白底問題   2017/07/26  */",
		"  .gcse-wrapper{",
		"     background: rgba(0,0,0,0)!important;   ",
		"  }",
		"  ",
		"  ",
		"  /*2017/07/07 上面的搜尋框*/",
		"  #old_search_searchbox{    ",
		"    background-color: rgba(255,255,255,0.2)!important;",
		"    color:#FFF !important;      ",
		"  }",
		"   #old_search_form *{    ",
		"    background-color: rgba(0,0,0,0)!important;",
		"    color:#FFF !important;",
		"  }",
		"  ",
		"  /*2017/07/07 搜尋框的熱門搜尋*/",
		"  .gcse-dropdown{",
		"     background-color: rgba(0,0,0,0.8)!important;",
		"     color:#FFF!important;     ",
		"  }",
		"  .gcse-suggest-tag a{",
		"    color : #87DFFF!important;    ",
		"  }",
		"  ",
		"  /*2017/07/07 下拉選單（搜尋方式）*/",
		"  .gcse-dropdown span{",
		"    color:#FFF!important; ",
		"  }",
		"  ",
		"  /* 2017/07/07 右邊的熱門推薦*/",
		"  .right-child{",
		"    background-color: hsla(0,0%,13%,0.50);",
		"    border: 1px solid rgba(255,255,255,0.39) !important;   ",
		"  }",
		"  .right-child a{",
		"    color : #87DFFF!important;    ",
		"  }"
	].join("\n");
if (false || (document.location.href.indexOf("https://forum.gamer.com.tw/opinion/") == 0))
	css += [
		"#BH-master , .BH-lbox{",
		"    color: #000!important;",
		"    background:#fff!important;",
		"  }",
		"  body{",
		"    color: #000!important;    ",
		"    background: url(https://i2.bahamut.com.tw/html_bg.gif) center top!important;",
		"  }"
	].join("\n");
if (false || (document.location.href.indexOf("https://forum.gamer.com.tw/vresult2") == 0))
	css += [
		"body{",
		"    color: #fff !important;   ",
		"  }",
		"  .std ,td{",
		"    color: #000 !important;",
		"  }"
	].join("\n");
if (false || (document.location.href.indexOf("https://forum.gamer.com.tw") == 0))
	css += [
		"/*每一筆 list*/",
		"  .forum_list{",
		"    background: rgba(0,0,0,0.4)!important;",
		"    border: 1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  .forum_list_title a{",
		"    color:#87DFFF!important;   ",
		"  }",
		"  .forum_list_info p a{",
		"    color:#fff!important;",
		"  }"
	].join("\n");
if (false || (document.location.href.indexOf("http://forum.gamer.com.tw/search") == 0) || (document.location.href.indexOf("https://forum.gamer.com.tw/search") == 0))
	css += [
		"/*服務選單*/",
		"  #BH-master{",
		"    background: rgba(0,0,0,0.4)!important;",
		"    border: 1px solid rgba(255,255,255,0.39)!important;",
		"  }",
		"  /*上面的選單【板上文章、找版外文章、找看版】*/",
		"  .gcse-tab-child{",
		"    color:#FFF!important;  ",
		"  }",
		"  /*選項【刪選作者、大人精華文章、主題、排序依據】*/",
		"  .gcse-forum span ,.gcse-forum option ,.gcse-forum #filter-subbsn,.gsc-orderby-label , .gsc-selected-option{",
		"    color:#FFF!important;",
		"  }",
		"  .gcse-forum .gcse-forum-select,.gsc-option-menu-container{",
		"    color:#FFF!important;",
		"    border: 1px solid rgba(255,255,255,0.39)!important;",
		"    color: #fff!important;",
		"  }",
		"  ",
		"  /*整體*/",
		"  .gsc-control-cse{",
		"    background: rgba(0,0,0,0)!important;",
		"    ",
		"  }",
		"  ",
		"  /*表格內的每一筆*/",
		"  .gsc-webResult{",
		"    background: rgba(0,0,0,0)!important; ",
		"    border-bottom:  1px solid rgba(255,255,255,0.4)!important;",
		"    ",
		"  }",
		"  .gs-title{/*標題超鏈接*/",
		"    color:#87DFFF!important;",
		"    text-decoration:none!important;",
		"  }",
		" .gs-bidi-start-align{/*內文*/",
		"    color:#FFF!important;",
		"  }",
		"  .gs-title b , .gs-bidi-start-align b{/*關鍵字的顏色*/",
		"    color:#AAFFCC !important;",
		"  }",
		"  ",
		"  /*右側區塊*/",
		"  .right-child{",
		"    background: rgba(0,0,0,0.4)!important;",
		"    border:  1px solid rgba(255,255,255,0.4)!important;",
		"    color:#FFF!important;",
		"  }",
		"  .right-child h3{",
		"    color:#FFF!important;",
		"  }",
		"  .right-child a{",
		"    color:#87DFFF!important;",
		"  }"
	].join("\n");
if (false || (document.location.href.indexOf("http://www.youtube.com/") == 0) || (document.location.href.indexOf("https://www.youtube.com/") == 0))
	css += [
		".controls , .ad-container{",
		"    display:block !important;",
		"    opacity :0 !important;",
		"    height: 0px !important;",
		"    pointer-events: none !important;    ",
		"  }"
	].join("\n");
if (typeof GM_addStyle != "undefined") {
	GM_addStyle(css);
} else if (typeof PRO_addStyle != "undefined") {
	PRO_addStyle(css);
} else if (typeof addStyle != "undefined") {
	addStyle(css);
} else {
	
	var heads = document.getElementsByTagName("head");
	if (heads.length > 0) {
		heads[0].appendChild(node);
	} else {
		// no head yet, stick it whereever
		document.documentElement.appendChild(node);
        //GM_addStyle(css);
	}
}
    
//},10 )
    

    setTimeout(function () {
       
        /*window.document.readystatechange = function () {
            if (document.readyState == "interactive" || document.readyState == "complete") {*/
                var node = document.createElement("style");
                node.type = "text/css";
                node.appendChild(document.createTextNode(css));
                document.documentElement.appendChild(node);
            /*}
        }*/

    }, 300);
    
})();
    
    